builds:
-
  main: ./itunes/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
archives:
-
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
